lcgcmt_installarea=without_installarea
CMTPATH=/besfs/users/caih/6.5.5:/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
CMT_tag=$(tag)
CMTROOT=/afs/ihep.ac.cn/bes3/offline/tool/CMT/v1r20
CMT_root=/afs/ihep.ac.cn/bes3/offline/tool/CMT/v1r20
CMTVERSION=v1r20
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/besfs/users/caih/6.5.5/InstallArea/share/bin:/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/share/bin:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/InstallArea/share/bin:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/InstallArea/share/bin:/besfs/users/caih/6.5.5/InstallArea/${CMTCONFIG}/bin:/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/${CMTCONFIG}/bin:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/InstallArea/${CMTCONFIG}/bin:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/XercesC/2.7.0/slc4_ia32_gcc34/bin:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/Python/2.4.2/slc4_ia32_gcc34/bin:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root/bin:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/gccxml/0.6.0_patch3/slc4_ia32_gcc34/bin:/afs/ihep.ac.cn/bes3/offline/tool/CMT/v1r20/${CMTBIN}:/usr/bin:/afs/ihep.ac.cn/users/c/caih/Backup:/afs/ihep.ac.cn/users/c/caih/root_data:/afs/ihep.ac.cn/users/c/caih/bin:/afs/ihep.ac.cn/users/c/caih/scripts:/usr/sue/bin:/bin:/usr/local/bin:/usr/local/bin/X11:/opt/ufal/bin:/usr/kerberos/bin:/opt/glite/bin:/opt/glite/externals/bin:/opt/lcg/bin:/opt/lcg/sbin:/opt/edg/bin:/opt/edg/sbin:/opt/globus/sbin:/opt/globus/bin:/opt/gpt/sbin:/opt/d-cache//srm/bin:/opt/d-cache//dcap/bin:/usr/java/jdk1.5.0_14/bin:/usr/X11R6/bin:${DAWN_HOME}/bin/Linux:${DAWN_HOME}/../bin/Linux:${DAVID_HOME}/bin/Linux:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/cernlib/2005/slc4_ia32_gcc34/bin
CLASSPATH=/afs/ihep.ac.cn/bes3/offline/tool/CMT/v1r20/java
debug_option=-g
cc=gcc
cflags= -fmessage-length=0 -fPIC 
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppflags= -fpermissive -fmessage-length=0     -pthread  -D_GNU_SOURCE -pthread -pipe -ansi -pedantic -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-long-long   -march=pentium -mcpu=pentium -pedantic-errors -O2
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags) -Wl,--no-undefined   -Wl,--export-dynamic 
cpplink=$(cpp) $(cpplinkflags)
for=g77
fflags=-fmessage-length=0 -O2    -fPIC -pipe -fno-second-underscore -Wall -W -Wsurprising -fPIC 
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=flex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=$(ExternalPolicy_root)/scripts/symlink.sh
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory  --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=cp -R 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(symlink_command)
cmt_uninstall_area_command=$(uninstall_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=i686-slc45-gcc346
OmegaKKAlg_tag=$(tag)
OMEGAKKALGROOT=/besfs/users/caih/6.5.5/mywork/OmegaKKAlg/OmegaKKAlg-00-00-03
OmegaKKAlg_root=/besfs/users/caih/6.5.5/mywork/OmegaKKAlg/OmegaKKAlg-00-00-03
OMEGAKKALGVERSION=OmegaKKAlg-00-00-03
OmegaKKAlg_cmtpath=/besfs/users/caih/6.5.5
OmegaKKAlg_offset=mywork
OmegaKKAlg_project=caih
OmegaKKAlg_project_release=6.5.5
BesPolicy_tag=$(tag)
BESPOLICYROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/BesPolicy/BesPolicy-01-05-03
BesPolicy_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/BesPolicy/BesPolicy-01-05-03
BESPOLICYVERSION=BesPolicy-01-05-03
BesPolicy_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
BesPolicy_project=Boss
BesPolicy_project_release=6.5.5
BesCxxPolicy_tag=$(tag)
BESCXXPOLICYROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/BesCxxPolicy/BesCxxPolicy-00-00-08
BesCxxPolicy_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/BesCxxPolicy/BesCxxPolicy-00-00-08
BESCXXPOLICYVERSION=BesCxxPolicy-00-00-08
BesCxxPolicy_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
BesCxxPolicy_project=Boss
BesCxxPolicy_project_release=6.5.5
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/GaudiPolicy
GaudiPolicy_root=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/GaudiPolicy
GAUDIPOLICYVERSION=v7r0
GaudiPolicy_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=GAUDI_v19r4
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Settings
LCG_Settings_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_52a_clhep2.0.4.5
SITEROOT=/afs/ihep.ac.cn/bes3/offline
LCG_home=${SITEROOT}/sw/lcg
LCG_external=$(LCG_home)/LCGCMT_52a_slc4_ia32_gcc34/external
LCG_releases=$(LCG_home)/app/releases
LCG_system=slc4_ia32_gcc34
LCG_platform=$(LCG_system)
copyInclude=cp -Rup 
dq="
genmap_cmd=$(ROOTSYS)/bin/genmap
BINDIR=$(tag)
vsDebug=2
merge_rootmap_cmd=${GaudiPolicy_root}/cmt/fragments/merge_files.py
libdirname=lib
bindirname=bin
cppdebugflags_s=-g
cppoptimized_s=-O2
cppprofiled_s=-pg
cppcoverage_s=-fprofile-arcs -ftest-coverage
cdebugflags_s=-g
ccoverage_s=-fprofile-arcs -ftest-coverage
fdebugflags_s=-g
foptimized_s=-O2
fprofiled_s=-pg
fcoverage_s=-fprofile-arcs -ftest-coverage
linkcoverage_s=-L/usr/lib/gcc-lib/i386-redhat-linux/3.2.3 -lgcc
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -ldl -Wl,--no-undefined    -Wl,-s 
libraryshr_linkopts=-fPIC -ldl -Wl,--no-undefined   
application_linkopts=-Wl,--export-dynamic 
genconfDir=genConf
merge_genconfDb_cmd=${GaudiPolicy_root}/cmt/fragments/merge_files.py
genconfig_configurableModuleName=gaudiconf
genconfig_configurableDefaultName=''
genconfig_configurableAlgorithm=configurable
genconfig_configurableAlgTool=configurable
genconfig_configurableAuditor=configurable
genconfig_configurableService=configurable
config_command=cp 
BesCxxPolicy_pp_cppflags= -DHAVE_PRETTY_FUNCTION -DHAVE_LONG_LONG -DHAVE_BOOL -DHAVE_EXPLICIT -DHAVE_MUTABLE -DHAVE_SIGNED -DHAVE_TYPENAME -DHAVE_NEW_STYLE_CASTS -DHAVE_DYNAMIC_CAST -DHAVE_TYPEID -DHAVE_ANSI_TEMPLATE_INSTANTIATION -DHAVE_TEMPLATE_DEFAULT_ARGS -DHAVE_BROKEN_TEMPLATE_RESCOPE -DHAVE_TEMPLATE_NULL_ARGS -DHAVE_TEMPLATE_NULL_SPEC -DHAVE_TEMPLATE_PARTIAL_SPEC -DHAVE_MEMBER_TEMPLATES -DHAVE_ANSI_OPERATOR_ARROW -DHAVE_NAMESPACES -DHAVE_NAMESPACE_STD -DHAVE_NEW_IOSTREAMS -DHAVE_OSTREAM_CHAR_OVERLOAD -DHAVE_ITERATOR_TRAITS -DHAVE_ITERATOR -DHAVE_REVERSE_ITERATOR_STYLE -DHAVE_CXX_STDC_HEADERS '-DPACKAGE_VERSION=$(q2)$(version)$(q2)' 
q2="
BesFortranPolicy_tag=$(tag)
BESFORTRANPOLICYROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/BesFortranPolicy/BesFortranPolicy-00-01-01
BesFortranPolicy_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/BesFortranPolicy/BesFortranPolicy-00-01-01
BESFORTRANPOLICYVERSION=BesFortranPolicy-00-01-01
BesFortranPolicy_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
BesFortranPolicy_project=Boss
BesFortranPolicy_project_release=6.5.5
f77_linkopts=-lg2c -lnsl -lcrypt -ldl
f90_home=$(f90_home_linux)
for90=$(for90_linux)
f90pp=$(f90pp_linux)
f90flags=$(f90flags_linux)
f90ppflags=$(f90ppflags_linux)
f90comp=$(f90comp_linux)
f90link=$(f90link_linux)
f90_linkopts=$(f90_linkopts_linux)
BesFortranPolicy_linkopts=$(f77_linkopts)
BesFortranPolicy_export_paths=$(PGI_libset)
BesPolicy_scripts= -s=$(BESPOLICYROOT)/share -s=$(BESPOLICYROOT)/src symlink.sh inverse_symlink.sh get_files 
symlink_command=symlink.sh
symlinknew=$(symlink_command)
copy_command=cp -R
remote_launcher=ssh -f 
application_fragment=application
library_fragment=library
library_no_share_fragment=library_no_share
install_include_filter=*.h
GaudiInterface_tag=$(tag)
GAUDIINTERFACEROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/GaudiInterface/GaudiInterface-01-03-05
GaudiInterface_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/GaudiInterface/GaudiInterface-01-03-05
GAUDIINTERFACEVERSION=GaudiInterface-01-03-05
GaudiInterface_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
GaudiInterface_offset=External
GaudiInterface_project=Boss
GaudiInterface_project_release=6.5.5
ExternalPolicy_tag=$(tag)
EXTERNALPOLICYROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/ExternalPolicy/ExternalPolicy-00-00-17
ExternalPolicy_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/ExternalPolicy/ExternalPolicy-00-00-17
EXTERNALPOLICYVERSION=ExternalPolicy-00-00-17
ExternalPolicy_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
ExternalPolicy_offset=External
ExternalPolicy_project=Boss
ExternalPolicy_project_release=6.5.5
ExternalComponents_tag=$(tag)
EXTERNALCOMPONENTSROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/ExternalComponents/ExternalComponents-00-00-32
ExternalComponents_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/ExternalComponents/ExternalComponents-00-00-32
EXTERNALCOMPONENTSVERSION=ExternalComponents-00-00-32
ExternalComponents_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
ExternalComponents_offset=External
ExternalComponents_project=Boss
ExternalComponents_project_release=6.5.5
GAUDI_DIR=${SITEROOT}/sw/Gaudi/rh72-gcc3.2/GAUDI_v12r0
GAUDI_RELEASE=0.12.1.4
base_URL=http://bes.web.cern.ch/Bes/GROUPS/SOFTWARE/OO/dist/
use_applications= $(cern_apps)
DOTFONTPATH=/lib/fonts/ttf
kits_dir=cmt/kits
zip_command=tar
GaudiKernel_tag=$(tag)
GAUDIKERNELROOT=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/GaudiKernel
GaudiKernel_root=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/GaudiKernel
GAUDIKERNELVERSION=v23r0
GaudiKernel_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4
GaudiKernel_project=GAUDI
GaudiKernel_project_release=GAUDI_v19r4
Reflex_tag=$(tag)
REFLEXROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/Reflex
Reflex_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_52a_clhep2.0.4.5
ROOT_tag=$(tag)
ROOTROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/ROOT
ROOT_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_52a_clhep2.0.4.5
GCCXML_tag=$(tag)
GCCXMLROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/GCCXML
GCCXML_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/GCCXML
GCCXMLVERSION=v1
GCCXML_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
GCCXML_offset=LCG_Interfaces
GCCXML_project=LCGCMT
GCCXML_project_release=LCGCMT_52a_clhep2.0.4.5
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Configuration
LCG_Configuration_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Configuration
LCG_CONFIGURATIONVERSION=*
LCG_Configuration_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_52a_clhep2.0.4.5
COOL_config_version=COOL_2_1_1
CORAL_config_version=CORAL_1_8_1
POOL_config_version=POOL_2_5_3
RELAX_config_version=RELAX_1_1_9
ROOT_config_version=5.14.00f
SEAL_config_version=SEAL_1_9_2
AIDA_config_version=3.2.1
Boost_config_version=1.33.1
Boost_file_version=1_33_1
bzlib_config_version=1.0.2
bz2lib_config_version=1.0.2
CASTOR_config_version=2.1.1-9
cernlib_config_version=2005
cgsigsoap_config_version=2.6-1.1.9
CLHEP_config_version=1.9.2.3
CppUnit_config_version=1.10.2_p2
cx_Oracle_config_version=4.1.2
Cygwin_config_version=1.5
dcache_client_config_version=1.7.0.31
EDGRLS_config_version=2.3.3
Expat_config_version=1.95.8
Frontier_Client_config_version=2.7.2
GCCXML_config_version=0.6.0_patch3
Geant4_config_version=4.8.3
gfal_config_version=1.7.7
globusrls_config_version=3.2.1
GSL_config_version=1.8
HepMC_config_version=1.26.02
HepPDT_config_version=2.02.02
HippoDraw_config_version=1.9.0
lfc_config_version=1.5.8
MathLib_config_version=1_0_0
mysql_config_version=5.0.18
mysqlpp_config_version=1.7.40_mysql.5.0.18
oracle_config_version=10.2.0.3
PCRE_config_version=4.4
Python_config_version=2.4.2
pyqt_config_version=3.13_python242
QMtest_config_version=2.3.0_python242
Qt_config_version=3.3.4
rx_config_version=1.5
scons_config_version=0.96.1
sqlite_config_version=3.3.5
uuid_config_version=1.38
vdt_config_version=1.2.3_globusrls215b
XercesC_config_version=2.7.0
zlib_config_version=1.1.4
pcre_config_version=4.4
GCCXML_native_version=$(GCCXML_config_version)
GCCXML_home=$(LCG_external)/gccxml/$(GCCXML_native_version)/$(LCG_system)
GCCXML_name=gccxml
LD_LIBRARY_PATH=/lib:/besfs/users/caih/6.5.5/InstallArea/${CMTCONFIG}/lib:/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/${CMTCONFIG}/lib:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/InstallArea/${CMTCONFIG}/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/cernlib/2005/slc4_ia32_gcc34/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/castor/2.1.1-9/slc4_ia32_gcc34/usr/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/XercesC/2.7.0/slc4_ia32_gcc34/lib:${STRING_DIR}/i386_linux26:${ALIST_DIR}/i386_linux26:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/HepPDT/2.02.02/slc4_ia32_gcc34/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/HepMC/1.26.02/slc4_ia32_gcc34/lib:/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/2.0.4.5/slc4_ia32_gcc346/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/Boost/1.33.1/slc4_ia32_gcc34/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root/lib:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/PI/PI_1_3_3/slc3_ia32_gcc323/lib:/usr/lib/gcc/i386-redhat-linux/3.4.6:/opt/c-ares/lib:/opt/glite/lib:/opt/glite/externals/lib:/opt/lcg/lib:/opt/edg/lib:/opt/globus/lib:/opt/d-cache//dcap/lib:/afs/ihep.ac.cn/bes3/offline/sw/packages/MySQL/5.0.45/slc4_ia32_gcc34/lib/mysql:/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/lib:/afs/ihep.ac.cn/bes3/offline/ExternalLib/packages/DIM/dim_v19r11/linux:/afs/ihep.ac.cn/bes3/offline/ExternalLib/packages/xmlrpc-c/xmlrpc-c-1.06.40/lib:/afs/ihep.ac.cn/bes3/offline/sw/packages/genbes/genbes-00-00-08/i386_linux26:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/Python/2.4.2/slc4_ia32_gcc34/lib:/afs/ihep.ac.cn/bes3/offline/sw/packages/sqlite/3.6.11/slc4_ia32_gcc34/lib:/afs/ihep.ac.cn/bes3/offline/sw/packages/LessTif/Motif1.2/lib:${BesGeant4_LIBDIR}/${G4SYSTEM}
GCCXML_export_paths=$(GCCXML_home)/bin $(GCCXML_home)/share 
ROOT_native_version=$(ROOT_config_version)
ROOT_base=$(LCG_external)/root/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)/root
ROOT_linkopts=-L$(ROOT_home)/lib -lCore -lCint -lTree -lpthread 
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lReflex
ROOTSYS=/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root
ROOT_name=root
list_cmd=$(LCG_Settings_root)/scripts/list_files.sh --type $(shlibsuffix) $(cernlib_home)/lib 
PYTHONPATH=/besfs/users/caih/6.5.5/InstallArea/python:/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/python:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/InstallArea/python:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/InstallArea/python:/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root/lib:/opt/lcg/lib:/opt/lcg/lib/python:/opt/edg/lib:/opt/edg/lib/python:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/PI/PI_1_3_3/slc3_ia32_gcc323/python
rootcint=rootcint
ROOT_export_paths= $(ROOT_home) 
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
Boost_tag=$(tag)
BOOSTROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/Boost
Boost_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/Boost
BOOSTVERSION=v1
Boost_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
Boost_offset=LCG_Interfaces
Boost_project=LCGCMT
Boost_project_release=LCGCMT_52a_clhep2.0.4.5
Boost_native_version=$(Boost_config_version)
Boost_home=$(LCG_external)/Boost/$(Boost_native_version)/$(LCG_system)
Boost_linkopts=-L$(Boost_home)/lib 
Boost_linkopts_python= -lboost_python-gcc 
Boost_linkopts_filesystem= -lboost_filesystem-gcc 
Boost_linkopts_regex= -lboost_regex-gcc 
Boost_linkopts_thread= -lboost_thread-gcc-mt 
Boost_linkopts_program_options= -lboost_program_options-gcc-mt 
Boost_export_paths=$(Boost_home)
Python_tag=$(tag)
PYTHONROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/Python
Python_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_52a_clhep2.0.4.5
Python_native_version=$(Python_config_version)
Python_version=2.4
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_version) -lutil -lpthread 
Python_export_paths=$(Python_home)
includes= $(ppcmd)"/besfs/users/caih/6.5.5/InstallArea/include/OmegaKKAlg" $(ppcmd)"/besfs/users/caih/6.5.5/InstallArea/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/InstallArea/include" $(use_includes)
GaudiKernel_linkopts= -lGaudiKernel 
GaudiKernel_stamps=${GAUDIKERNELROOT}/${BINDIR}/GaudiKernel.stamp 
GaudiKernel_linker_library=GaudiKernel
GaudiKernel_reflex_selection_file= $(GAUDIKERNELROOT)/dict/dictionary.xml 
GaudiKernel_rootmap=$(CMTINSTALLAREA)/$(tag)/lib/rootmap
GaudiKernel_reflex_options=  $(gccxmlopts) --select=$(GAUDIKERNELROOT)/dict/dictionary.xml  --gccxmlpath=$(GCCXML_home)/bin
GaudiKernelDict_dependencies=$(GaudiKernel_linker_library) GaudiKernelGen
GaudiKernelDict_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(GaudiKernel_linkopts) $(GaudiKernelDict_use_linkopts) 
GaudiKernelDict_use_linkopts=$(use_linkopts)
genconfig_cmd=$(GaudiKernel_cmtpath)/$(GAUDI_installarea_prefix)/$(tag)/bin/genconf.exe
GAUDIEXE=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/InstallArea/i386_linux26/bin/Gaudi.exe
Gaudi=${GAUDIEXE}
DstEvent_tag=$(tag)
DSTEVENTROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/DstEvent/DstEvent-00-02-47
DstEvent_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/DstEvent/DstEvent-00-02-47
DSTEVENTVERSION=DstEvent-00-02-47
DstEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
DstEvent_offset=Event
DstEvent_project=Boss
DstEvent_project_release=6.5.5
BesCLHEP_tag=$(tag)
BESCLHEPROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/BesCLHEP/BesCLHEP-00-00-06
BesCLHEP_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/BesCLHEP/BesCLHEP-00-00-06
BESCLHEPVERSION=BesCLHEP-00-00-06
BesCLHEP_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
BesCLHEP_offset=External
BesCLHEP_project=Boss
BesCLHEP_project_release=6.5.5
CLHEP_tag=$(tag)
CLHEPROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/CLHEP
CLHEP_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/CLHEP
CLHEPVERSION=v1
CLHEP_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
CLHEP_offset=LCG_Interfaces
CLHEP_project=LCGCMT
CLHEP_project_release=LCGCMT_52a_clhep2.0.4.5
CLHEP_native_version=2.0.4.5
CLHEP_home=/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/2.0.4.5/slc4_ia32_gcc346
CLHEP_linkopts=-L$(CLHEP_home)/lib         -lCLHEP-Cast-$(CLHEP_native_version)        -lCLHEP-Evaluator-$(CLHEP_native_version)        -lCLHEP-Exceptions-$(CLHEP_native_version)        -lCLHEP-GenericFunctions-$(CLHEP_native_version)        -lCLHEP-Geometry-$(CLHEP_native_version)        -lCLHEP-Random-$(CLHEP_native_version)        -lCLHEP-RandomObjects-$(CLHEP_native_version)        -lCLHEP-RefCount-$(CLHEP_native_version)         -lCLHEP-Vector-$(CLHEP_native_version)        -lCLHEP-Matrix-$(CLHEP_native_version)   -L${ALIST_DIR}/i386_linux26 -lAlist -L${STRING_DIR}/i386_linux26 -lString 
CLHEP_name=clhep
CLHEP_export_paths=$(CLHEP_home)/include $(CLHEP_home)/lib
HepMC_tag=$(tag)
HEPMCROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/HepMC
HepMC_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/HepMC
HEPMCVERSION=v1
HepMC_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
HepMC_offset=LCG_Interfaces
HepMC_project=LCGCMT
HepMC_project_release=LCGCMT_52a_clhep2.0.4.5
HepMC_native_version=$(HepMC_config_version)
HepMC_home=$(LCG_external)/HepMC/$(HepMC_native_version)/$(LCG_system)
HepMC_linkopts=-L$(HepMC_home)/lib -lHepMC  
HepMC_export_paths=$(HepMC_home)/include $(HepMC_home)/lib
HepPDT_tag=$(tag)
HEPPDTROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/HepPDT
HepPDT_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/HepPDT
HEPPDTVERSION=v1
HepPDT_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
HepPDT_offset=LCG_Interfaces
HepPDT_project=LCGCMT
HepPDT_project_release=LCGCMT_52a_clhep2.0.4.5
HepPDT_native_version=$(HepPDT_config_version)
HepPDT_home=$(LCG_external)/HepPDT/$(HepPDT_native_version)/$(LCG_system)
HepPDT_linkopts=-L$(HepPDT_home)/lib -lHepPDT -lHepPID 
HepPDT_export_paths=$(HepPDT_home)/include $(HepPDT_home)/lib
BesExternalArea_tag=$(tag)
BESEXTERNALAREAROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/BesExternalArea/BesExternalArea-00-00-18
BesExternalArea_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/BesExternalArea/BesExternalArea-00-00-18
BESEXTERNALAREAVERSION=BesExternalArea-00-00-18
BesExternalArea_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
BesExternalArea_offset=External
BesExternalArea_project=Boss
BesExternalArea_project_release=6.5.5
LCG_ROOT=${SITEROOT}/sw/lcg
LCG_EXTERNAL=${LCG_ROOT}/external
LCG_app_system=rh73_gcc32
LCG_ext_system=rh73_gcc32
BES_EXTERNAL=${SITEROOT}/sw/external
BESTESTDATA=${SITEROOT}/bes/offline/data/testfile
BESCALDATA=${SITEROOT}/bes/offline/data/${BES_RELEASE}
COMMON_PACKAGES=${SITEROOT}/sw/packages
ALIST_DIR=/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/Alist/Alist-00-00-04
STRING_DIR=/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/String/String-00-00-03
CLHEP_pp_cppflags= -DCLHEP_MAX_MIN_DEFINED -DCLHEP_ABS_DEFINED -DCLHEP_SQR_DEFINED 
CLHEP_pp_fflags= -DCLHEP_MAX_MIN_DEFINED -DCLHEP_ABS_DEFINED -DCLHEP_SQR_DEFINED 
EventModel_tag=$(tag)
EVENTMODELROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/EventModel/EventModel-01-05-31
EventModel_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/EventModel/EventModel-01-05-31
EVENTMODELVERSION=EventModel-01-05-31
EventModel_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
EventModel_offset=Event
EventModel_project=Boss
EventModel_project_release=6.5.5
EventModel_linkopts= -L$(bin) -lEventModel  
DstEvent_linkopts= -L$(bin) -lDstEvent  
EvtRecEvent_tag=$(tag)
EVTRECEVENTROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/EvtRecEvent/EvtRecEvent-00-01-04
EvtRecEvent_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/EvtRecEvent/EvtRecEvent-00-01-04
EVTRECEVENTVERSION=EvtRecEvent-00-01-04
EvtRecEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
EvtRecEvent_offset=Event
EvtRecEvent_project=Boss
EvtRecEvent_project_release=6.5.5
EvTimeEvent_tag=$(tag)
EVTIMEEVENTROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/EvTimeEvent/EvTimeEvent-00-00-08
EvTimeEvent_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/EvTimeEvent/EvTimeEvent-00-00-08
EVTIMEEVENTVERSION=EvTimeEvent-00-00-08
EvTimeEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
EvTimeEvent_offset=Event
EvTimeEvent_project=Boss
EvTimeEvent_project_release=6.5.5
MdcGeomSvc_tag=$(tag)
MDCGEOMSVCROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Mdc/MdcGeomSvc/MdcGeomSvc-00-01-36
MdcGeomSvc_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Mdc/MdcGeomSvc/MdcGeomSvc-00-01-36
MDCGEOMSVCVERSION=MdcGeomSvc-00-01-36
MdcGeomSvc_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
MdcGeomSvc_offset=Mdc
MdcGeomSvc_project=Boss
MdcGeomSvc_project_release=6.5.5
calibUtil_tag=$(tag)
CALIBUTILROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Calibration/calibUtil/calibUtil-00-00-29
calibUtil_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Calibration/calibUtil/calibUtil-00-00-29
CALIBUTILVERSION=calibUtil-00-00-29
calibUtil_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
calibUtil_offset=Calibration
calibUtil_project=Boss
calibUtil_project_release=6.5.5
facilities_tag=$(tag)
FACILITIESROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Calibration/facilities/facilities-00-00-01
facilities_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Calibration/facilities/facilities-00-00-01
FACILITIESVERSION=facilities-00-00-01
facilities_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
facilities_offset=Calibration
facilities_project=Boss
facilities_project_release=6.5.5
facilities_linkopts= -lfacilities 
xmlBase_tag=$(tag)
XMLBASEROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Calibration/xmlBase/xmlBase-00-00-02
xmlBase_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Calibration/xmlBase/xmlBase-00-00-02
XMLBASEVERSION=xmlBase-00-00-02
xmlBase_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
xmlBase_offset=Calibration
xmlBase_project=Boss
xmlBase_project_release=6.5.5
XercesC_tag=$(tag)
XERCESCROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/XercesC
XercesC_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/XercesC
XERCESCVERSION=v1
XercesC_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
XercesC_offset=LCG_Interfaces
XercesC_project=LCGCMT
XercesC_project_release=LCGCMT_52a_clhep2.0.4.5
XercesC_native_version=$(XercesC_config_version)
XercesC_home=$(LCG_external)/XercesC/$(XercesC_native_version)/$(LCG_system)
XercesC_linkopts=-L$(XercesC_home)/lib -lxerces-c -lxerces-depdom -lpthread
XercesC_warnings=-w -Wno-unused
XercesC_export_paths= $(XercesC_home)/include $(XercesC_home)/lib
xmlBase_linkopts=-L$(XMLBASEROOT)/$(xmlBase_tag) -lxmlBase  
rdbModel_tag=$(tag)
RDBMODELROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Calibration/rdbModel/rdbModel-00-00-13
rdbModel_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Calibration/rdbModel/rdbModel-00-00-13
RDBMODELVERSION=rdbModel-00-00-13
rdbModel_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
rdbModel_offset=Calibration
rdbModel_project=Boss
rdbModel_project_release=6.5.5
MYSQL_tag=$(tag)
MYSQLROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/MYSQL/MYSQL-00-00-07
MYSQL_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/MYSQL/MYSQL-00-00-07
MYSQLVERSION=MYSQL-00-00-07
MYSQL_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
MYSQL_offset=External
MYSQL_project=Boss
MYSQL_project_release=6.5.5
MYSQL_native_version=5.0.45
MYSQLBASE=${COMMON_PACKAGES}/MySQL/$(MYSQL_native_version)/slc4_ia32_gcc34
MYSQL_linkopts=-L$(MYSQLBASE)/lib/mysql -lmysqlclient -lz 
rdbModel_linkopts=-L$(RDBMODELROOT)/$(rdbModel_tag) -lrdbModel  
BesROOT_tag=$(tag)
BESROOTROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/BesROOT/BesROOT-00-00-06
BesROOT_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/BesROOT/BesROOT-00-00-06
BESROOTVERSION=BesROOT-00-00-06
BesROOT_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
BesROOT_offset=External
BesROOT_project=Boss
BesROOT_project_release=6.5.5
CASTOR_tag=$(tag)
CASTORROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/CASTOR
CASTOR_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/CASTOR
CASTORVERSION=v1
CASTOR_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
CASTOR_offset=LCG_Interfaces
CASTOR_project=LCGCMT
CASTOR_project_release=LCGCMT_52a_clhep2.0.4.5
CASTOR_native_version=$(CASTOR_config_version)
CASTOR_name=castor
CASTOR_home=$(LCG_external)/$(CASTOR_name)/$(CASTOR_native_version)/$(LCG_system)/usr
CASTOR_libdir=lib
CASTOR_linkopts=-L$(CASTOR_home)/$(CASTOR_libdir) -lshift 
CASTOR_export_paths=$(CASTOR_home)/include $(CASTOR_home)/$(CASTOR_libdir)
rootBasicLibs=-L$(ROOT_home)/lib -lCore -lCint -lTree -lRFIO
rootMathLibs=-L$(ROOT_home)/lib   -lMLP -lMinuit -lMatrix -lPhysics -lHistPainter -lHist -lRint
rootGraphicsLibs=-L$(ROOT_home)/lib -lGraf -lGraf3d -lGpad -lHtml -lPostscript -lGui -lGX11TTF -lGX11 -lASImageGui -lASImage -lGeom -lGeomPainter -lX3d -lRGL -lVMC 
rootTableLibs=-L$(ROOT_home)/lib -lTable
rootSTLDictLibs= -L${ROOT_home}/lib -ldequeDict -llistDict -lmapDict -lmap2Dict -lmultimapDict -lmultimap2Dict -lmultisetDict -lsetDict -lvectorDict 
BesROOT_linkopts= $(rootMathLibs) $(rootBasicLibs) $(rootGraphicsLibs) $(rootTableLibs) $(rootSTLDictLibs) 
DatabaseSvc_tag=$(tag)
DATABASESVCROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Database/DatabaseSvc/DatabaseSvc-00-00-14
DatabaseSvc_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Database/DatabaseSvc/DatabaseSvc-00-00-14
DATABASESVCVERSION=DatabaseSvc-00-00-14
DatabaseSvc_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
DatabaseSvc_offset=Database
DatabaseSvc_project=Boss
DatabaseSvc_project_release=6.5.5
Sqlite_tag=$(tag)
SQLITEROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/Sqlite/Sqlite-00-00-01
Sqlite_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/Sqlite/Sqlite-00-00-01
SQLITEVERSION=Sqlite-00-00-01
Sqlite_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
Sqlite_offset=External
Sqlite_project=Boss
Sqlite_project_release=6.5.5
Sqlite_native_version=3.6.11
SQLITEBASE=${COMMON_PACKAGES}/sqlite/$(Sqlite_native_version)/slc4_ia32_gcc34
Sqlite_linkopts=-L$(SQLITEBASE)/lib -lsqlite3 
DatabaseSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
DatabaseSvcstamps= $(bin)/DatabaseSvcsetup.make 
DatabaseSvc_scripts= -s=../share -s=$(DATABASESVCROOT)/share dbupdate.py 
use_scripts= $(DatabaseSvc_scripts) 
install_scripts_dependencies=DatabaseSvc_check_install_scripts
MYSQL_HOST=localhost
MYSQL_METATABLE=metadata_v0r1
calibUtil_linkopts=-L$(CALIBUTILROOT)/$(calibUtil_tag) -lcalibUtil  
CalibData_tag=$(tag)
CALIBDATAROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Calibration/CalibData/CalibData-00-00-42
CalibData_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Calibration/CalibData/CalibData-00-00-42
CALIBDATAVERSION=CalibData-00-00-42
CalibData_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
CalibData_offset=Calibration
CalibData_project=Boss
CalibData_project_release=6.5.5
CalibData_linkopts= -L$(bin) -lCalibData  
MdcGeomSvcLib_files=*.cxx
MdcGeomSvc_dependencies= MdcGeomSvcLib
MdcGeomSvcstamps= $(bin)/MdcGeomSvcLib.stamp $(bin)/MdcGeomSvcsetup.make 
MdcGeomSvc_linkopts= -L$(bin) -lMdcGeomSvcLib
MdcGeomSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
RelTable_tag=$(tag)
RELTABLEROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/RelTable/RelTable-00-00-02
RelTable_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/RelTable/RelTable-00-00-02
RELTABLEVERSION=RelTable-00-00-02
RelTable_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
RelTable_offset=Event
RelTable_project=Boss
RelTable_project_release=6.5.5
Identifier_tag=$(tag)
IDENTIFIERROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/DetectorDescription/Identifier/Identifier-00-02-10
Identifier_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/DetectorDescription/Identifier/Identifier-00-02-10
IDENTIFIERVERSION=Identifier-00-02-10
Identifier_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
Identifier_offset=DetectorDescription
Identifier_project=Boss
Identifier_project_release=6.5.5
Identifier_linkopts= -L$(bin) -lIdentifier  
EvTimeEvent_linkopts= -L$(bin) -lEvTimeEvent  
MdcRecEvent_tag=$(tag)
MDCRECEVENTROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Mdc/MdcRecEvent/MdcRecEvent-00-05-12
MdcRecEvent_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Mdc/MdcRecEvent/MdcRecEvent-00-05-12
MDCRECEVENTVERSION=MdcRecEvent-00-05-12
MdcRecEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
MdcRecEvent_offset=Mdc
MdcRecEvent_project=Boss
MdcRecEvent_project_release=6.5.5
MdcRecEvent_linkopts= -L$(bin) -lMdcRecEvent  
TofRecEvent_tag=$(tag)
TOFRECEVENTROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Tof/TofRecEvent/TofRecEvent-00-02-14
TofRecEvent_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Tof/TofRecEvent/TofRecEvent-00-02-14
TOFRECEVENTVERSION=TofRecEvent-00-02-14
TofRecEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
TofRecEvent_offset=Tof
TofRecEvent_project=Boss
TofRecEvent_project_release=6.5.5
TofRecEvent_linkopts= -L$(bin) -lTofRecEvent  
EmcRecEventModel_tag=$(tag)
EMCRECEVENTMODELROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Emc/EmcRecEventModel/EmcRecEventModel-01-01-18
EmcRecEventModel_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Emc/EmcRecEventModel/EmcRecEventModel-01-01-18
EMCRECEVENTMODELVERSION=EmcRecEventModel-01-01-18
EmcRecEventModel_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
EmcRecEventModel_offset=Emc
EmcRecEventModel_project=Boss
EmcRecEventModel_project_release=6.5.5
EmcRecGeoSvc_tag=$(tag)
EMCRECGEOSVCROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Emc/EmcRecGeoSvc/EmcRecGeoSvc-01-01-07
EmcRecGeoSvc_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Emc/EmcRecGeoSvc/EmcRecGeoSvc-01-01-07
EMCRECGEOSVCVERSION=EmcRecGeoSvc-01-01-07
EmcRecGeoSvc_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
EmcRecGeoSvc_offset=Emc
EmcRecGeoSvc_project=Boss
EmcRecGeoSvc_project_release=6.5.5
ROOTGeo_tag=$(tag)
ROOTGEOROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/DetectorDescription/ROOTGeo/ROOTGeo-00-00-14
ROOTGeo_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/DetectorDescription/ROOTGeo/ROOTGeo-00-00-14
ROOTGEOVERSION=ROOTGeo-00-00-14
ROOTGeo_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
ROOTGeo_offset=DetectorDescription
ROOTGeo_project=Boss
ROOTGeo_project_release=6.5.5
GdmlToRoot_tag=$(tag)
GDMLTOROOTROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/GdmlToRoot/GdmlToRoot-00-00-11
GdmlToRoot_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/GdmlToRoot/GdmlToRoot-00-00-11
GDMLTOROOTVERSION=GdmlToRoot-00-00-11
GdmlToRoot_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
GdmlToRoot_offset=External
GdmlToRoot_project=Boss
GdmlToRoot_project_release=6.5.5
GdmlToRoot_path=${COMMON_PACKAGES}/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML
GdmlToRoot_LIBDIR=${GdmlToRoot_path}/lib
GdmlToRoot_linkopts=-L$(GdmlToRoot_LIBDIR)  -lProcesses -lSaxana -lWriter -lEvaluator -lProcessor -lSubscribers
GdmlManagement_tag=$(tag)
GDMLMANAGEMENTROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/DetectorDescription/GdmlManagement/GdmlManagement-00-00-27
GdmlManagement_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/DetectorDescription/GdmlManagement/GdmlManagement-00-00-27
GDMLMANAGEMENTVERSION=GdmlManagement-00-00-27
GdmlManagement_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
GdmlManagement_offset=DetectorDescription
GdmlManagement_project=Boss
GdmlManagement_project_release=6.5.5
ROOTGeoLib_files=*.cxx
ROOTGeo_dependencies= ROOTGeoLib
ROOTGeostamps= $(bin)/ROOTGeoLib.stamp $(bin)/ROOTGeosetup.make 
ROOTGeo_linkopts= -L$(bin) -lROOTGeoLib
ROOTGeo_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
EmcRecGeoSvcLib_files=*.cxx
EmcRecGeoSvc_dependencies= EmcRecGeoSvcLib
EmcRecGeoSvcstamps= $(bin)/EmcRecGeoSvcLib.stamp $(bin)/EmcRecGeoSvcsetup.make 
EmcRecGeoSvc_linkopts= -L$(bin) -lEmcRecGeoSvcLib
EmcRecGeoSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
EmcRecEventModel_linkopts= -L$(bin) -lEmcRecEventModel  
MucRecEvent_tag=$(tag)
MUCRECEVENTROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Muc/MucRecEvent/MucRecEvent-00-02-49
MucRecEvent_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Muc/MucRecEvent/MucRecEvent-00-02-49
MUCRECEVENTVERSION=MucRecEvent-00-02-49
MucRecEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
MucRecEvent_offset=Muc
MucRecEvent_project=Boss
MucRecEvent_project_release=6.5.5
ExtEvent_tag=$(tag)
EXTEVENTROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/ExtEvent/ExtEvent-00-00-13
ExtEvent_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/ExtEvent/ExtEvent-00-00-13
EXTEVENTVERSION=ExtEvent-00-00-13
ExtEvent_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
ExtEvent_offset=Event
ExtEvent_project=Boss
ExtEvent_project_release=6.5.5
ExtEvent_linkopts= -L$(bin) -lExtEvent  
MucGeomSvc_tag=$(tag)
MUCGEOMSVCROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Muc/MucGeomSvc/MucGeomSvc-00-02-25
MucGeomSvc_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Muc/MucGeomSvc/MucGeomSvc-00-02-25
MUCGEOMSVCVERSION=MucGeomSvc-00-02-25
MucGeomSvc_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
MucGeomSvc_offset=Muc
MucGeomSvc_project=Boss
MucGeomSvc_project_release=6.5.5
G4Geo_tag=$(tag)
G4GEOROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/DetectorDescription/G4Geo/G4Geo-00-00-10
G4Geo_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/DetectorDescription/G4Geo/G4Geo-00-00-10
G4GEOVERSION=G4Geo-00-00-10
G4Geo_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
G4Geo_offset=DetectorDescription
G4Geo_project=Boss
G4Geo_project_release=6.5.5
BesGeant4_tag=$(tag)
BESGEANT4ROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/BesGeant4/BesGeant4-00-00-06
BesGeant4_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/BesGeant4/BesGeant4-00-00-06
BESGEANT4VERSION=BesGeant4-00-00-06
BesGeant4_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
BesGeant4_offset=External
BesGeant4_project=Boss
BesGeant4_project_release=6.5.5
LessTif_tag=$(tag)
LESSTIFROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/LessTif/LessTif-00-00-05
LessTif_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/LessTif/LessTif-00-00-05
LESSTIFVERSION=LessTif-00-00-05
LessTif_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
LessTif_offset=External
LessTif_project=Boss
LessTif_project_release=6.5.5
Xt_tag=$(tag)
XTROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/Xt/Xt-00-00-02
Xt_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/Xt/Xt-00-00-02
XTVERSION=Xt-00-00-02
Xt_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
Xt_offset=External
Xt_project=Boss
Xt_project_release=6.5.5
Xt_native_version=X11R6
Xt_home=/usr/$(Xt_native_version)
Xt_linkopts=-L$(Xt_home)/lib -lXt -lSM -lICE -lXpm -lX11 -lXi -lXext
LessTif_native_version_rh61=2.0
LessTif_native_version_rh73=2.1
LessTif_DIR_rh61=$(Xt_home)
LessTif_DIR_rh73=$(Xt_home)
LessTif_native_version=1.2
LessTif_DIR=$(COMMON_PACKAGES)
LessTif_home=$(LessTif_DIR)/LessTif/Motif$(LessTif_native_version)
LessTif_linkopts= -L$(LessTif_home)/lib -lXm 
BesGeant4_PACKAGE=/afs/ihep.ac.cn/bes3/offline/ExternalLib/packages/geant4
BesGeant4_VERSION=4.9.3.p01
BesGeant4_ARCH=slc4_ia32_gcc346
BesGeant4_PATH=${BesGeant4_PACKAGE}/$(BesGeant4_VERSION)/$(BesGeant4_ARCH)/geant4.9.3.p01
G4INCLUDE=/afs/ihep.ac.cn/bes3/offline/ExternalLib/packages/geant4/4.9.3.p01/slc4_ia32_gcc346/geant4.9.3.p01/include
BesGeant4_LIBDIR=/afs/ihep.ac.cn/bes3/offline/ExternalLib/packages/geant4/4.9.3.p01/slc4_ia32_gcc346/geant4.9.3.p01/lib
G4SYSTEM=Linux-g++
BesGeant4_DATA=/afs/ihep.ac.cn/bes3/offline/ExternalLib/packages/geant4/4.9.3.p01/slc4_ia32_gcc346/geant4.9.3.p01/data
G4LEDATA=${BesGeant4_DATA}/G4EMLOW6.9
NeutronHPCrossSections=${BesGeant4_DATA}/G4NDL3.13
G4LEVELGAMMADATA=${BesGeant4_DATA}/PhotonEvaporation2.0
G4RADIOACTIVEDATA=${BesGeant4_DATA}/RadiativeDecay3.2
G4ABLADATA=${BesGeant4_DATA}/G4ABLA3.0
G4REALSURFACEDATA=${BesGeant4_DATA}/RealSurface1.0
G4NEUTRONHPDATA=${BesGeant4_DATA}/G4NDL3.13
BesGeant4_linkopts= -L${BesGeant4_LIBDIR}/$(G4SYSTEM)       -lG4baryons       -lG4biasing       -lG4bosons       -lG4brep       -lG4csg       -lG4cuts       -lG4decay       -lG4detector       -lG4detscorer       -lG4detutils       -lG4digits       -lG4emadjoint       -lG4emhighenergy       -lG4emlowenergy       -lG4empolar       -lG4emstandard       -lG4emutils       -lG4error_propagation       -lG4event       -lG4FR       -lG4gdml       -lG4geombias       -lG4geomBoolean       -lG4geomdivision       -lG4geometrymng       -lG4geomtext       -lG4gflash       -lG4gl2ps       -lG4globman       -lG4GMocren       -lG4graphics_reps       -lG4had_im_r_matrix       -lG4had_lll_fis       -lG4had_mod_man       -lG4had_mod_util       -lG4had_muon_nuclear       -lG4had_neu_hp       -lG4had_preequ_exciton       -lG4hadronic_ablation       -lG4hadronic_abrasion       -lG4hadronic_bert_cascade       -lG4hadronic_binary       -lG4hadronic_body_ci       -lG4hadronic_coherent_elastic       -lG4hadronic_crosec_ci       -lG4hadronic_deex_evaporation       -lG4hadronic_deex_fermi_breakup       -lG4hadronic_deex_fission       -lG4hadronic_deex_gem_evaporation       -lG4hadronic_deex_handler       -lG4hadronic_deex_management       -lG4hadronic_deex_multifragmentation       -lG4hadronic_deex_photon_evaporation       -lG4hadronic_deex_util       -lG4hadronic_em_dissociation       -lG4hadronic_fragm_ci       -lG4hadronic_HE       -lG4hadronic_hetcpp_evaporation       -lG4hadronic_hetcpp_utils       -lG4hadronic_incl_cascade       -lG4hadronic_interface_ci       -lG4hadronic_iso       -lG4hadronic_LE       -lG4hadronic_leading_particle       -lG4hadronic_mgt       -lG4hadronic_proc       -lG4hadronic_proc_ci       -lG4hadronic_qgstring       -lG4hadronic_qmd       -lG4hadronic_radioactivedecay       -lG4hadronic_RPG       -lG4hadronic_stop       -lG4hadronic_util       -lG4hadronic_xsect       -lG4had_string_diff       -lG4had_string_frag       -lG4had_string_man       -lG4had_theo_max       -lG4hepnumerics       -lG4hits       -lG4intercoms       -lG4ions       -lG4leptons       -lG4magneticfield       -lG4materials       -lG4mctruth       -lG4mesons       -lG4modeling       -lG4muons       -lG4navigation       -lG4OpenGL       -lG4optical       -lG4parameterisation       -lG4partadj       -lG4partman       -lG4partutils       -lG4phys_builders       -lG4phys_lists       -lG4procman       -lG4RayTracer       -lG4readout       -lG4run       -lG4scoring       -lG4shortlived       -lG4specsolids       -lG4tracking       -lG4track       -lG4transportation       -lG4Tree       -lG4UIbasic       -lG4UIcommon       -lG4UIGAG       -lG4visHepRep       -lG4vis_management       -lG4visXXX       -lG4volumes       -lG4VRML       -lG4xrays       -lXm
BesGeant4_cppflags= -W -Wall -ansi -pedantic -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -pipe -O2 -fPIC  -DG4OPTIMIZE -DG4VERBOSE -DG4_STORE_TRAJECTORY -DG4UI_USE_TCSH  -DG4VIS_USE -DG4VIS_USE_OPENGLX -DG4VIS_USE_OPENGL
DAWN_HOME=${SITEROOT}/sw/contrib/DAWN/3.85
DAVID_HOME=${SITEROOT}/sw/contrib/DAVID/1.34
DAWN_BSD_UNIX_DOMAIN=1
DAWN_GUI_ALWAYS=1
G4VIS_USE_DAWN=1
G4VIS_USE_DAWNFILE=1
G4DAWNFILE_VIEWER=dawn
G4VIS_USE_OPENGLX=1
G4VIS_USE=1
GdmlToG4_tag=$(tag)
GDMLTOG4ROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/GdmlToG4/GdmlToG4-00-00-08
GdmlToG4_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/GdmlToG4/GdmlToG4-00-00-08
GDMLTOG4VERSION=GdmlToG4-00-00-08
GdmlToG4_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
GdmlToG4_offset=External
GdmlToG4_project=Boss
GdmlToG4_project_release=6.5.5
GdmlToG4_path=${COMMON_PACKAGES}/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML
GdmlToG4_LIBDIR=${GdmlToG4_path}/lib
GdmlToG4_linkopts=-L$(GdmlToG4_LIBDIR) -lProcesses -lSaxana -lWriter -lG4Evaluator -lG4Processor -lG4Subscribers -lG4Writer
G4GeoLib_files=*.cxx
G4Geo_dependencies= G4GeoLib
G4Geostamps= $(bin)/G4GeoLib.stamp $(bin)/G4Geosetup.make 
G4Geo_linkopts= -L$(bin) -lG4GeoLib
G4Geo_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
MucGeomSvcLib_files=*.cxx
MucGeomSvc_dependencies= MucGeomSvcLib
MucGeomSvcstamps= $(bin)/MucGeomSvcLib.stamp $(bin)/MucGeomSvcsetup.make 
MucGeomSvc_linkopts= -L$(bin) -lMucGeomSvcLib
MucGeomSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
MucRecEvent_linkopts= -L$(bin) -lMucRecEvent  
EvtRecEvent_linkopts= -L$(bin) -lEvtRecEvent  
VertexFit_tag=$(tag)
VERTEXFITROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Analysis/VertexFit/VertexFit-00-02-54
VertexFit_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Analysis/VertexFit/VertexFit-00-02-54
VERTEXFITVERSION=VertexFit-00-02-54
VertexFit_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
VertexFit_offset=Analysis
VertexFit_project=Boss
VertexFit_project_release=6.5.5
MagneticField_tag=$(tag)
MAGNETICFIELDROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/MagneticField/MagneticField-00-01-32
MagneticField_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/MagneticField/MagneticField-00-01-32
MAGNETICFIELDVERSION=MagneticField-00-01-32
MagneticField_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
MagneticField_project=Boss
MagneticField_project_release=6.5.5
BesTimerSvc_tag=$(tag)
BESTIMERSVCROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Utilities/BesTimerSvc/BesTimerSvc-00-00-11
BesTimerSvc_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Utilities/BesTimerSvc/BesTimerSvc-00-00-11
BESTIMERSVCVERSION=BesTimerSvc-00-00-11
BesTimerSvc_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
BesTimerSvc_offset=Utilities
BesTimerSvc_project=Boss
BesTimerSvc_project_release=6.5.5
BesTimerSvcLib_files=*.cxx
BesTimerSvc_dependencies= BesTimerSvcLib
BesTimerSvcstamps= $(bin)/BesTimerSvcLib.stamp $(bin)/BesTimerSvcsetup.make 
BesTimerSvc_linkopts= -L$(bin) -lBesTimerSvcLib
BesTimerSvc_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
MagneticField_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
MagneticFieldstamps= $(bin)/MagneticFieldsetup.make 
VertexFit_linkopts=-L$(bin) -lVertexFit   -lVertexFit 
VertexFit_cppflags= -w 
VertexFit_stamps=${VERTEXFITROOT}/${BINDIR}/VertexFit.stamp 
ParticleID_tag=$(tag)
PARTICLEIDROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Analysis/ParticleID/ParticleID-00-04-48
ParticleID_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Analysis/ParticleID/ParticleID-00-04-48
PARTICLEIDVERSION=ParticleID-00-04-48
ParticleID_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
ParticleID_offset=Analysis
ParticleID_project=Boss
ParticleID_project_release=6.5.5
CERNLIB_tag=$(tag)
CERNLIBROOT=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/cernlib
CERNLIB_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/External/CERNLIB/CERNLIB-01-02-01
CERNLIBVERSION=v1
CERNLIB_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
CERNLIB_offset=External
CERNLIB_project=Boss
CERNLIB_project_release=6.5.5
cernlib_tag=$(tag)
cernlib_root=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/LCG_Interfaces/cernlib
cernlib_cmtpath=/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5
cernlib_offset=LCG_Interfaces
cernlib_project=LCGCMT
cernlib_project_release=LCGCMT_52a_clhep2.0.4.5
cernlib_native_version=$(cernlib_config_version)
cernlib_base=$(LCG_external)/cernlib/$(cernlib_native_version)
cernlib_home=$(cernlib_base)/$(LCG_system)
graflib=-L$(cernlib_home)/lib  -lgraflib -lgrafX11 -lpacklib -L/usr/X11R6/lib -lX11 
cernlib_linkopts= -L$(cernlib_home)/lib -lphotos202 -lpythia6205  -lpdflib804 -lmathlib -lpawlib -llapack3 -lblas -lgraflib -lgrafX11 -lpacklib -lmathlib -lphtools -lkernlib -L/usr/X11R6/lib -lX11  -lg2c $(BesShift_linkopts) -lshift -lnsl -lcrypt -ldl -lg2c
cernlib_fflags= -DCERNLIB_TYPE -DCERNLIB_LINUX
cernlib_export_paths=$(cernlib_home)/include $(cernlib_home)/bin $(cernlib_home)/lib
CERN=/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/cernlib/2005/slc4_ia32_gcc34
CERN_LEVEL=.
ParticleID_linkopts= -L$(bin) -lParticleID  
ParticleID_cppflags= -DYDEBUG -DMEMWATCH -DMEMWATCH_STDIO  -Df2cFortran -w
ParticleID_fflags=  -fno-automatic -ffixed-line-length-132 -fbackslash  -w
McTruth_tag=$(tag)
MCTRUTHROOT=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/McTruth/McTruth-00-02-19
McTruth_root=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/McTruth/McTruth-00-02-19
MCTRUTHVERSION=McTruth-00-02-19
McTruth_cmtpath=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5
McTruth_offset=Event
McTruth_project=Boss
McTruth_project_release=6.5.5
McTruth_linkopts= -L$(bin) -lMcTruth  
OmegaKKAlg_shlibflags=$(componentshr_linkopts) $(use_linkopts) 
OmegaKKAlgstamps= $(bin)/OmegaKKAlgsetup.make 
OmegaKKAlg_runtime= -s=../share *.txt  
use_runtime= $(OmegaKKAlg_runtime) 
install_runtime_dependencies=OmegaKKAlg_check_install_runtime
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
BesCxxPolicyDir=${BESCXXPOLICYROOT}/${BINDIR}
BesPolicyDir=${BESPOLICYROOT}/${BINDIR}
ExternalPolicyDir=${EXTERNALPOLICYROOT}/${BINDIR}
GaudiKernelDir=${GAUDIKERNELROOT}/${BINDIR}
GaudiInterfaceDir=${GAUDIINTERFACEROOT}/${BINDIR}
BesExternalAreaDir=${BESEXTERNALAREAROOT}/${BINDIR}
BesCLHEPDir=${BESCLHEPROOT}/${BINDIR}
EventModelDir=${EVENTMODELROOT}/${BINDIR}
DstEventDir=${DSTEVENTROOT}/${BINDIR}
facilitiesDir=${FACILITIESROOT}/${BINDIR}
xmlBaseDir=${XMLBASEROOT}/${BINDIR}
MYSQLDir=${MYSQLROOT}/${BINDIR}
rdbModelDir=${RDBMODELROOT}/${BINDIR}
SqliteDir=${SQLITEROOT}/${BINDIR}
DatabaseSvcDir=${DATABASESVCROOT}/${BINDIR}
calibUtilDir=${CALIBUTILROOT}/${BINDIR}
CalibDataDir=${CALIBDATAROOT}/${BINDIR}
MdcGeomSvcDir=${MDCGEOMSVCROOT}/${BINDIR}
RelTableDir=${RELTABLEROOT}/${BINDIR}
IdentifierDir=${IDENTIFIERROOT}/${BINDIR}
EvTimeEventDir=${EVTIMEEVENTROOT}/${BINDIR}
MdcRecEventDir=${MDCRECEVENTROOT}/${BINDIR}
TofRecEventDir=${TOFRECEVENTROOT}/${BINDIR}
GdmlToRootDir=${GDMLTOROOTROOT}/${BINDIR}
GdmlManagementDir=${GDMLMANAGEMENTROOT}/${BINDIR}
ROOTGeoDir=${ROOTGEOROOT}/${BINDIR}
EmcRecGeoSvcDir=${EMCRECGEOSVCROOT}/${BINDIR}
EmcRecEventModelDir=${EMCRECEVENTMODELROOT}/${BINDIR}
ExtEventDir=${EXTEVENTROOT}/${BINDIR}
LessTifDir=${LESSTIFROOT}/${BINDIR}
BesGeant4Dir=${BESGEANT4ROOT}/${BINDIR}
GdmlToG4Dir=${GDMLTOG4ROOT}/${BINDIR}
G4GeoDir=${G4GEOROOT}/${BINDIR}
MucGeomSvcDir=${MUCGEOMSVCROOT}/${BINDIR}
MucRecEventDir=${MUCRECEVENTROOT}/${BINDIR}
EvtRecEventDir=${EVTRECEVENTROOT}/${BINDIR}
BesTimerSvcDir=${BESTIMERSVCROOT}/${BINDIR}
MagneticFieldDir=${MAGNETICFIELDROOT}/${BINDIR}
VertexFitDir=${VERTEXFITROOT}/${BINDIR}
ParticleIDDir=${PARTICLEIDROOT}/${BINDIR}
McTruthDir=${MCTRUTHROOT}/${BINDIR}
OmegaKKAlgDir=${OMEGAKKALGROOT}/${BINDIR}
old_dir=`echo $(OmegaKKAlg_project)/$(OmegaKKAlg_project_release) | sed -e 's#//#/#g'`
old_base=`echo $(OmegaKKAlg_cmtpath) | sed -e 's#/$(old_dir)##'`
sedcmd='s#$(old_base)##' -e 's#^/##' -e 's#/$##' -e 's#[^/]*#..#g'
new_base=`/bin/pwd | sed -e ${sedcmd}`
new_fincludes=`( echo $(includes) | sed -e 's#$(old_base)#$(new_base)#g')`
fincludes=`cmt show macro_value new_fincludes`
tag=i386_linux26
package=OmegaKKAlg
version=OmegaKKAlg-00-00-03
PACKAGE_ROOT=$(OMEGAKKALGROOT)
srcdir=../src
bin=../$(OmegaKKAlg_tag)/
javabin=../classes/
mgrdir=cmt
project=caih
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(Boss_installarea_prefix)/$(CMTCONFIG)/lib $(Boss_installarea_prefix)/share/lib $(Boss_installarea_prefix)/share/bin $(caih_installarea_prefix)/$(CMTCONFIG)/lib $(caih_installarea_prefix)/share/lib $(caih_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(OmegaKKAlg_linkopts)  $(VertexFit_linkopts)  $(ParticleID_linkopts)  $(EvtRecEvent_linkopts)  $(MdcRecEvent_linkopts)  $(TofRecEvent_linkopts)  $(EmcRecEventModel_linkopts)  $(MucRecEvent_linkopts)  $(ExtEvent_linkopts)  $(DstEvent_linkopts)  $(EvTimeEvent_linkopts)  $(MdcGeomSvc_linkopts)  $(MagneticField_linkopts)  $(McTruth_linkopts)  $(EventModel_linkopts)  $(calibUtil_linkopts)  $(rdbModel_linkopts)  $(xmlBase_linkopts)  $(CalibData_linkopts)  $(facilities_linkopts)  $(DatabaseSvc_linkopts)  $(RelTable_linkopts)  $(EmcRecGeoSvc_linkopts)  $(MucGeomSvc_linkopts)  $(G4Geo_linkopts)  $(Identifier_linkopts)  $(ROOTGeo_linkopts)  $(BesTimerSvc_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GdmlToG4_linkopts)  $(BesGeant4_linkopts)  $(BesCLHEP_linkopts)  $(MYSQL_linkopts)  $(Sqlite_linkopts)  $(GdmlToRoot_linkopts)  $(GdmlManagement_linkopts)  $(LessTif_linkopts)  $(BesExternalArea_linkopts)  $(ExternalPolicy_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(BesFortranPolicy_linkopts)  $(Reflex_linkopts)  $(BesROOT_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(HepMC_linkopts)  $(CLHEP_linkopts)  $(HepPDT_linkopts)  $(XercesC_linkopts)  $(CERNLIB_linkopts)  $(CASTOR_linkopts)  $(cernlib_linkopts)  $(LCG_Settings_linkopts)  $(ExternalComponents_linkopts)  $(LCG_Configuration_linkopts)  $(Xt_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
Boss_installarea_prefix=$(cmt_installarea_prefix)
Boss_installarea_prefix_remove=$(Boss_installarea_prefix)
caih_installarea_prefix=$(cmt_installarea_prefix)
caih_installarea_prefix_remove=$(caih_installarea_prefix)
cmt_installarea_linkopts= -L/besfs/users/caih/6.5.5/$(caih_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/$(Boss_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib 
caih_install_include= /besfs/users/caih/6.5.5/$(caih_installarea_prefix)/include 
Boss_install_include= /afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/$(Boss_installarea_prefix)/include 
GAUDI_install_include= /afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/$(GAUDI_installarea_prefix)/include 
GAUDI_install_python=/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/$(GAUDI_installarea_prefix)/python
Boss_install_python=/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/$(Boss_installarea_prefix)/python
caih_install_python=/besfs/users/caih/6.5.5/$(caih_installarea_prefix)/python
JOBOPTSEARCHPATH=,/besfs/users/caih/6.5.5/InstallArea/jobOptions,/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/jobOptions,/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/InstallArea/jobOptions,/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/InstallArea/jobOptions
DATAPATH=/besfs/users/caih/6.5.5/InstallArea/share:/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/share:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/InstallArea/share:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/InstallArea/share:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/PartPropSvc/share
XMLPATH=/besfs/users/caih/6.5.5/InstallArea/XML:/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/XML:/afs/ihep.ac.cn/bes3/offline/sw/Gaudi/slc4_ia32_gcc34-clhep2.0.4.5/GAUDI_v19r4/InstallArea/XML:/afs/ihep.ac.cn/bes3/offline/sw/lcg/app/releases/LCGCMT/LCGCMT_52a_clhep2.0.4.5/InstallArea/XML
constituents= install_includes  OmegaKKAlg install_runtime config install_includes 
CMTINSTALLAREA=/besfs/users/caih/6.5.5/$(cmt_installarea_prefix)
use_requirements=requirements $(CMTROOT)/mgr/requirements $(VERTEXFITROOT)/cmt/requirements $(PARTICLEIDROOT)/cmt/requirements $(EVTRECEVENTROOT)/cmt/requirements $(MDCRECEVENTROOT)/cmt/requirements $(TOFRECEVENTROOT)/cmt/requirements $(EMCRECEVENTMODELROOT)/cmt/requirements $(MUCRECEVENTROOT)/cmt/requirements $(EXTEVENTROOT)/cmt/requirements $(DSTEVENTROOT)/cmt/requirements $(EVTIMEEVENTROOT)/cmt/requirements $(MDCGEOMSVCROOT)/cmt/requirements $(MAGNETICFIELDROOT)/cmt/requirements $(MCTRUTHROOT)/cmt/requirements $(EVENTMODELROOT)/cmt/requirements $(CALIBUTILROOT)/cmt/requirements $(RDBMODELROOT)/cmt/requirements $(XMLBASEROOT)/cmt/requirements $(CALIBDATAROOT)/cmt/requirements $(FACILITIESROOT)/cmt/requirements $(DATABASESVCROOT)/cmt/requirements $(RELTABLEROOT)/cmt/requirements $(EMCRECGEOSVCROOT)/cmt/requirements $(MUCGEOMSVCROOT)/cmt/requirements $(G4GEOROOT)/cmt/requirements $(IDENTIFIERROOT)/cmt/requirements $(ROOTGEOROOT)/cmt/requirements $(BESTIMERSVCROOT)/cmt/requirements $(BESPOLICYROOT)/cmt/requirements $(BESCXXPOLICYROOT)/cmt/requirements $(GAUDIINTERFACEROOT)/cmt/requirements $(GDMLTOG4ROOT)/cmt/requirements $(BESGEANT4ROOT)/cmt/requirements $(BESCLHEPROOT)/cmt/requirements $(MYSQLROOT)/cmt/requirements $(SQLITEROOT)/cmt/requirements $(GDMLTOROOTROOT)/cmt/requirements $(GDMLMANAGEMENTROOT)/cmt/requirements $(LESSTIFROOT)/cmt/requirements $(BESEXTERNALAREAROOT)/cmt/requirements $(EXTERNALPOLICYROOT)/cmt/requirements $(GAUDIKERNELROOT)/cmt/requirements $(GAUDIPOLICYROOT)/cmt/requirements $(BESFORTRANPOLICYROOT)/cmt/requirements $(REFLEXROOT)/cmt/requirements $(BESROOTROOT)/cmt/requirements $(ROOTROOT)/cmt/requirements $(GCCXMLROOT)/cmt/requirements $(BOOSTROOT)/cmt/requirements $(PYTHONROOT)/cmt/requirements $(HEPMCROOT)/cmt/requirements $(CLHEPROOT)/cmt/requirements $(HEPPDTROOT)/cmt/requirements $(XERCESCROOT)/cmt/requirements $(CERNLIBROOT)/cmt/requirements $(CASTORROOT)/cmt/requirements $(CERNLIBROOT)/cmt/requirements $(LCG_SETTINGSROOT)/cmt/requirements $(EXTERNALCOMPONENTSROOT)/cmt/requirements $(LCG_CONFIGURATIONROOT)/cmt/requirements $(XTROOT)/cmt/requirements 
use_includes= $(ppcmd)"include_dirs" $(ppcmd)"apply_pattern" $(ppcmd)"component_library" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Analysis/VertexFit/VertexFit-00-02-54/VertexDbSvc" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Analysis/VertexFit/VertexFit-00-02-54/src/test" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/VertexFit" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/ParticleID" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/EvtRecEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Mdc/MdcRecEvent/MdcRecEvent-00-05-12" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/MdcRecEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Tof/TofRecEvent/TofRecEvent-00-02-14" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/TofRecEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Emc/EmcRecEventModel/EmcRecEventModel-01-01-18" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/EmcRecEventModel" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/MucRecEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/ExtEvent/ExtEvent-00-00-13" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/ExtEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/DstEvent/DstEvent-00-02-47" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/DstEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/EvTimeEvent/EvTimeEvent-00-00-08" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/EvTimeEvent" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Mdc/MdcGeomSvc/MdcGeomSvc-00-01-36" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/MdcGeomSvc" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/MagneticField" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/McTruth/McTruth-00-02-19/McTruth" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/McTruth" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/EventModel/EventModel-01-05-31" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/EventModel" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/calibUtil" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/rdbModel" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/xmlBase" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/CalibData" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/facilities" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/DatabaseSvc" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Event/RelTable/RelTable-00-00-02" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/RelTable" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/Emc/EmcRecGeoSvc/EmcRecGeoSvc-01-01-07" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/EmcRecGeoSvc" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/MucGeomSvc" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/G4Geo" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/DetectorDescription/Identifier/Identifier-00-02-10" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/Identifier" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/ROOTGeo" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/InstallArea/include/BesTimerSvc" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/Boss/6.5.5/BesCxxPolicy/BesCxxPolicy-00-00-08" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Saxana" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Saxana/Saxana" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Processes/" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Processes/Processes" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Schema" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Schema/Schema" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Writer/Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/G4Binding/G4Evaluator" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/G4Binding/G4Evaluator/G4Evaluator" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/G4Binding/G4Processor" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/G4Binding/G4Processor/G4Processor" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/G4Binding/G4Subscribers" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/G4Binding/G4Subscribers/G4Subscribers" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/G4Binding/G4Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/G4Binding/G4Writer/G4Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/ExternalLib/packages/geant4/4.9.3.p01/slc4_ia32_gcc346/geant4.9.3.p01/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/Alist/Alist-00-00-04" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/String/String-00-00-03" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/MySQL/5.0.45/slc4_ia32_gcc34/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/sqlite/3.6.11/slc4_ia32_gcc34/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Saxana" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Saxana/Saxana" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Processes" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Processes/Processes" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Schema" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Schema/Schema" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/Common/Writer/Writer" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/ROOTBinding/Processor" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/ROOTBinding/Processor/Processor" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/ROOTBinding/Subscribers" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/ROOTBinding/Subscribers/Subscribers" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/ROOTBinding/Evaluator" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/BesGDML/2.8.0/slc4_ia32_gcc346-clhep2.0.4.5/CPPGDML/ROOTBinding/Evaluator/Evaluator" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/LessTif/Motif1.2/include" $(ppcmd)"$(BesFortranPolicy_root)/src" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root/include" $(ppcmd)"$(BesROOT_root)/src" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/root/5.14.00f/slc4_ia32_gcc34/root/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/Boost/1.33.1/slc4_ia32_gcc34/include/boost-1_33_1" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/Python/2.4.2/slc4_ia32_gcc34/include/python2.4" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/HepMC/1.26.02/slc4_ia32_gcc34/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/packages/CLHEP/2.0.4.5/slc4_ia32_gcc346/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/HepPDT/2.02.02/slc4_ia32_gcc34/include" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/XercesC/2.7.0/slc4_ia32_gcc34/include" $(ppcmd)"$(CERNLIB_root)/src" $(ppcmd)"/afs/ihep.ac.cn/bes3/offline/sw/lcg/LCGCMT_52a_slc4_ia32_gcc34/external/cernlib/2005/slc4_ia32_gcc34/include" $(ppcmd)"$(Xt_root)/src" $(ppcmd)"/usr/X11R6/include" 
use_fincludes= $(use_includes)
use_stamps= $(OmegaKKAlg_stamps)  $(VertexFit_stamps)  $(ParticleID_stamps)  $(EvtRecEvent_stamps)  $(MdcRecEvent_stamps)  $(TofRecEvent_stamps)  $(EmcRecEventModel_stamps)  $(MucRecEvent_stamps)  $(ExtEvent_stamps)  $(DstEvent_stamps)  $(EvTimeEvent_stamps)  $(MdcGeomSvc_stamps)  $(MagneticField_stamps)  $(McTruth_stamps)  $(EventModel_stamps)  $(calibUtil_stamps)  $(rdbModel_stamps)  $(xmlBase_stamps)  $(CalibData_stamps)  $(facilities_stamps)  $(DatabaseSvc_stamps)  $(RelTable_stamps)  $(EmcRecGeoSvc_stamps)  $(MucGeomSvc_stamps)  $(G4Geo_stamps)  $(Identifier_stamps)  $(ROOTGeo_stamps)  $(BesTimerSvc_stamps)  $(BesPolicy_stamps)  $(BesCxxPolicy_stamps)  $(GaudiInterface_stamps)  $(GdmlToG4_stamps)  $(BesGeant4_stamps)  $(BesCLHEP_stamps)  $(MYSQL_stamps)  $(Sqlite_stamps)  $(GdmlToRoot_stamps)  $(GdmlManagement_stamps)  $(LessTif_stamps)  $(BesExternalArea_stamps)  $(ExternalPolicy_stamps)  $(GaudiKernel_stamps)  $(GaudiPolicy_stamps)  $(BesFortranPolicy_stamps)  $(Reflex_stamps)  $(BesROOT_stamps)  $(ROOT_stamps)  $(GCCXML_stamps)  $(Boost_stamps)  $(Python_stamps)  $(HepMC_stamps)  $(CLHEP_stamps)  $(HepPDT_stamps)  $(XercesC_stamps)  $(CERNLIB_stamps)  $(CASTOR_stamps)  $(cernlib_stamps)  $(LCG_Settings_stamps)  $(ExternalComponents_stamps)  $(LCG_Configuration_stamps)  $(Xt_stamps) 
use_cflags=  $(OmegaKKAlg_cflags)  $(VertexFit_cflags)  $(ParticleID_cflags)  $(EvtRecEvent_cflags)  $(MdcRecEvent_cflags)  $(TofRecEvent_cflags)  $(EmcRecEventModel_cflags)  $(MucRecEvent_cflags)  $(ExtEvent_cflags)  $(DstEvent_cflags)  $(EvTimeEvent_cflags)  $(MdcGeomSvc_cflags)  $(MagneticField_cflags)  $(McTruth_cflags)  $(EventModel_cflags)  $(calibUtil_cflags)  $(rdbModel_cflags)  $(xmlBase_cflags)  $(CalibData_cflags)  $(facilities_cflags)  $(DatabaseSvc_cflags)  $(RelTable_cflags)  $(EmcRecGeoSvc_cflags)  $(MucGeomSvc_cflags)  $(G4Geo_cflags)  $(Identifier_cflags)  $(ROOTGeo_cflags)  $(BesTimerSvc_cflags)  $(BesPolicy_cflags)  $(BesCxxPolicy_cflags)  $(GaudiInterface_cflags)  $(GdmlToG4_cflags)  $(BesGeant4_cflags)  $(BesCLHEP_cflags)  $(MYSQL_cflags)  $(Sqlite_cflags)  $(GdmlToRoot_cflags)  $(GdmlManagement_cflags)  $(LessTif_cflags)  $(BesExternalArea_cflags)  $(ExternalPolicy_cflags)  $(GaudiKernel_cflags)  $(GaudiPolicy_cflags)  $(BesFortranPolicy_cflags)  $(Reflex_cflags)  $(BesROOT_cflags)  $(ROOT_cflags)  $(Boost_cflags)  $(Python_cflags)  $(HepMC_cflags)  $(CLHEP_cflags)  $(HepPDT_cflags)  $(XercesC_cflags)  $(CERNLIB_cflags)  $(CASTOR_cflags)  $(cernlib_cflags)  $(LCG_Settings_cflags)  $(ExternalComponents_cflags)  $(LCG_Configuration_cflags)  $(Xt_cflags) 
use_pp_cflags=  $(OmegaKKAlg_pp_cflags)  $(VertexFit_pp_cflags)  $(ParticleID_pp_cflags)  $(EvtRecEvent_pp_cflags)  $(MdcRecEvent_pp_cflags)  $(TofRecEvent_pp_cflags)  $(EmcRecEventModel_pp_cflags)  $(MucRecEvent_pp_cflags)  $(ExtEvent_pp_cflags)  $(DstEvent_pp_cflags)  $(EvTimeEvent_pp_cflags)  $(MdcGeomSvc_pp_cflags)  $(MagneticField_pp_cflags)  $(McTruth_pp_cflags)  $(EventModel_pp_cflags)  $(calibUtil_pp_cflags)  $(rdbModel_pp_cflags)  $(xmlBase_pp_cflags)  $(CalibData_pp_cflags)  $(facilities_pp_cflags)  $(DatabaseSvc_pp_cflags)  $(RelTable_pp_cflags)  $(EmcRecGeoSvc_pp_cflags)  $(MucGeomSvc_pp_cflags)  $(G4Geo_pp_cflags)  $(Identifier_pp_cflags)  $(ROOTGeo_pp_cflags)  $(BesTimerSvc_pp_cflags)  $(BesPolicy_pp_cflags)  $(BesCxxPolicy_pp_cflags)  $(GaudiInterface_pp_cflags)  $(GdmlToG4_pp_cflags)  $(BesGeant4_pp_cflags)  $(BesCLHEP_pp_cflags)  $(MYSQL_pp_cflags)  $(Sqlite_pp_cflags)  $(GdmlToRoot_pp_cflags)  $(GdmlManagement_pp_cflags)  $(LessTif_pp_cflags)  $(BesExternalArea_pp_cflags)  $(ExternalPolicy_pp_cflags)  $(GaudiKernel_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(BesFortranPolicy_pp_cflags)  $(Reflex_pp_cflags)  $(BesROOT_pp_cflags)  $(ROOT_pp_cflags)  $(Boost_pp_cflags)  $(Python_pp_cflags)  $(HepMC_pp_cflags)  $(CLHEP_pp_cflags)  $(HepPDT_pp_cflags)  $(XercesC_pp_cflags)  $(CERNLIB_pp_cflags)  $(CASTOR_pp_cflags)  $(cernlib_pp_cflags)  $(LCG_Settings_pp_cflags)  $(ExternalComponents_pp_cflags)  $(LCG_Configuration_pp_cflags)  $(Xt_pp_cflags) 
use_cppflags=  $(OmegaKKAlg_cppflags)  $(VertexFit_cppflags)  $(ParticleID_cppflags)  $(EvtRecEvent_cppflags)  $(MdcRecEvent_cppflags)  $(TofRecEvent_cppflags)  $(EmcRecEventModel_cppflags)  $(MucRecEvent_cppflags)  $(ExtEvent_cppflags)  $(DstEvent_cppflags)  $(EvTimeEvent_cppflags)  $(MdcGeomSvc_cppflags)  $(MagneticField_cppflags)  $(McTruth_cppflags)  $(EventModel_cppflags)  $(calibUtil_cppflags)  $(rdbModel_cppflags)  $(xmlBase_cppflags)  $(CalibData_cppflags)  $(facilities_cppflags)  $(DatabaseSvc_cppflags)  $(RelTable_cppflags)  $(EmcRecGeoSvc_cppflags)  $(MucGeomSvc_cppflags)  $(G4Geo_cppflags)  $(Identifier_cppflags)  $(ROOTGeo_cppflags)  $(BesTimerSvc_cppflags)  $(BesPolicy_cppflags)  $(BesCxxPolicy_cppflags)  $(GaudiInterface_cppflags)  $(GdmlToG4_cppflags)  $(BesGeant4_cppflags)  $(BesCLHEP_cppflags)  $(MYSQL_cppflags)  $(Sqlite_cppflags)  $(GdmlToRoot_cppflags)  $(GdmlManagement_cppflags)  $(LessTif_cppflags)  $(BesExternalArea_cppflags)  $(ExternalPolicy_cppflags)  $(GaudiKernel_cppflags)  $(GaudiPolicy_cppflags)  $(BesFortranPolicy_cppflags)  $(Reflex_cppflags)  $(BesROOT_cppflags)  $(ROOT_cppflags)  $(Boost_cppflags)  $(Python_cppflags)  $(HepMC_cppflags)  $(CLHEP_cppflags)  $(HepPDT_cppflags)  $(XercesC_cppflags)  $(CERNLIB_cppflags)  $(CASTOR_cppflags)  $(cernlib_cppflags)  $(LCG_Settings_cppflags)  $(ExternalComponents_cppflags)  $(LCG_Configuration_cppflags)  $(Xt_cppflags) 
use_pp_cppflags=  $(OmegaKKAlg_pp_cppflags)  $(VertexFit_pp_cppflags)  $(ParticleID_pp_cppflags)  $(EvtRecEvent_pp_cppflags)  $(MdcRecEvent_pp_cppflags)  $(TofRecEvent_pp_cppflags)  $(EmcRecEventModel_pp_cppflags)  $(MucRecEvent_pp_cppflags)  $(ExtEvent_pp_cppflags)  $(DstEvent_pp_cppflags)  $(EvTimeEvent_pp_cppflags)  $(MdcGeomSvc_pp_cppflags)  $(MagneticField_pp_cppflags)  $(McTruth_pp_cppflags)  $(EventModel_pp_cppflags)  $(calibUtil_pp_cppflags)  $(rdbModel_pp_cppflags)  $(xmlBase_pp_cppflags)  $(CalibData_pp_cppflags)  $(facilities_pp_cppflags)  $(DatabaseSvc_pp_cppflags)  $(RelTable_pp_cppflags)  $(EmcRecGeoSvc_pp_cppflags)  $(MucGeomSvc_pp_cppflags)  $(G4Geo_pp_cppflags)  $(Identifier_pp_cppflags)  $(ROOTGeo_pp_cppflags)  $(BesTimerSvc_pp_cppflags)  $(BesPolicy_pp_cppflags)  $(BesCxxPolicy_pp_cppflags)  $(GaudiInterface_pp_cppflags)  $(GdmlToG4_pp_cppflags)  $(BesGeant4_pp_cppflags)  $(BesCLHEP_pp_cppflags)  $(MYSQL_pp_cppflags)  $(Sqlite_pp_cppflags)  $(GdmlToRoot_pp_cppflags)  $(GdmlManagement_pp_cppflags)  $(LessTif_pp_cppflags)  $(BesExternalArea_pp_cppflags)  $(ExternalPolicy_pp_cppflags)  $(GaudiKernel_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(BesFortranPolicy_pp_cppflags)  $(Reflex_pp_cppflags)  $(BesROOT_pp_cppflags)  $(ROOT_pp_cppflags)  $(Boost_pp_cppflags)  $(Python_pp_cppflags)  $(HepMC_pp_cppflags)  $(CLHEP_pp_cppflags)  $(HepPDT_pp_cppflags)  $(XercesC_pp_cppflags)  $(CERNLIB_pp_cppflags)  $(CASTOR_pp_cppflags)  $(cernlib_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(ExternalComponents_pp_cppflags)  $(LCG_Configuration_pp_cppflags)  $(Xt_pp_cppflags) 
use_fflags=  $(OmegaKKAlg_fflags)  $(VertexFit_fflags)  $(ParticleID_fflags)  $(EvtRecEvent_fflags)  $(MdcRecEvent_fflags)  $(TofRecEvent_fflags)  $(EmcRecEventModel_fflags)  $(MucRecEvent_fflags)  $(ExtEvent_fflags)  $(DstEvent_fflags)  $(EvTimeEvent_fflags)  $(MdcGeomSvc_fflags)  $(MagneticField_fflags)  $(McTruth_fflags)  $(EventModel_fflags)  $(calibUtil_fflags)  $(rdbModel_fflags)  $(xmlBase_fflags)  $(CalibData_fflags)  $(facilities_fflags)  $(DatabaseSvc_fflags)  $(RelTable_fflags)  $(EmcRecGeoSvc_fflags)  $(MucGeomSvc_fflags)  $(G4Geo_fflags)  $(Identifier_fflags)  $(ROOTGeo_fflags)  $(BesTimerSvc_fflags)  $(BesPolicy_fflags)  $(BesCxxPolicy_fflags)  $(GaudiInterface_fflags)  $(GdmlToG4_fflags)  $(BesGeant4_fflags)  $(BesCLHEP_fflags)  $(MYSQL_fflags)  $(Sqlite_fflags)  $(GdmlToRoot_fflags)  $(GdmlManagement_fflags)  $(LessTif_fflags)  $(BesExternalArea_fflags)  $(ExternalPolicy_fflags)  $(GaudiKernel_fflags)  $(GaudiPolicy_fflags)  $(BesFortranPolicy_fflags)  $(Reflex_fflags)  $(BesROOT_fflags)  $(ROOT_fflags)  $(Boost_fflags)  $(Python_fflags)  $(HepMC_fflags)  $(CLHEP_fflags)  $(HepPDT_fflags)  $(XercesC_fflags)  $(CERNLIB_fflags)  $(CASTOR_fflags)  $(cernlib_fflags)  $(LCG_Settings_fflags)  $(ExternalComponents_fflags)  $(LCG_Configuration_fflags)  $(Xt_fflags) 
use_pp_fflags=  $(OmegaKKAlg_pp_fflags)  $(VertexFit_pp_fflags)  $(ParticleID_pp_fflags)  $(EvtRecEvent_pp_fflags)  $(MdcRecEvent_pp_fflags)  $(TofRecEvent_pp_fflags)  $(EmcRecEventModel_pp_fflags)  $(MucRecEvent_pp_fflags)  $(ExtEvent_pp_fflags)  $(DstEvent_pp_fflags)  $(EvTimeEvent_pp_fflags)  $(MdcGeomSvc_pp_fflags)  $(MagneticField_pp_fflags)  $(McTruth_pp_fflags)  $(EventModel_pp_fflags)  $(calibUtil_pp_fflags)  $(rdbModel_pp_fflags)  $(xmlBase_pp_fflags)  $(CalibData_pp_fflags)  $(facilities_pp_fflags)  $(DatabaseSvc_pp_fflags)  $(RelTable_pp_fflags)  $(EmcRecGeoSvc_pp_fflags)  $(MucGeomSvc_pp_fflags)  $(G4Geo_pp_fflags)  $(Identifier_pp_fflags)  $(ROOTGeo_pp_fflags)  $(BesTimerSvc_pp_fflags)  $(BesPolicy_pp_fflags)  $(BesCxxPolicy_pp_fflags)  $(GaudiInterface_pp_fflags)  $(GdmlToG4_pp_fflags)  $(BesGeant4_pp_fflags)  $(BesCLHEP_pp_fflags)  $(MYSQL_pp_fflags)  $(Sqlite_pp_fflags)  $(GdmlToRoot_pp_fflags)  $(GdmlManagement_pp_fflags)  $(LessTif_pp_fflags)  $(BesExternalArea_pp_fflags)  $(ExternalPolicy_pp_fflags)  $(GaudiKernel_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(BesFortranPolicy_pp_fflags)  $(Reflex_pp_fflags)  $(BesROOT_pp_fflags)  $(ROOT_pp_fflags)  $(Boost_pp_fflags)  $(Python_pp_fflags)  $(HepMC_pp_fflags)  $(CLHEP_pp_fflags)  $(HepPDT_pp_fflags)  $(XercesC_pp_fflags)  $(CERNLIB_pp_fflags)  $(CASTOR_pp_fflags)  $(cernlib_pp_fflags)  $(LCG_Settings_pp_fflags)  $(ExternalComponents_pp_fflags)  $(LCG_Configuration_pp_fflags)  $(Xt_pp_fflags) 
use_libraries= $(VertexFit_libraries)  $(ParticleID_libraries)  $(EvtRecEvent_libraries)  $(MdcRecEvent_libraries)  $(TofRecEvent_libraries)  $(EmcRecEventModel_libraries)  $(MucRecEvent_libraries)  $(ExtEvent_libraries)  $(DstEvent_libraries)  $(EvTimeEvent_libraries)  $(MdcGeomSvc_libraries)  $(MagneticField_libraries)  $(McTruth_libraries)  $(EventModel_libraries)  $(calibUtil_libraries)  $(rdbModel_libraries)  $(xmlBase_libraries)  $(CalibData_libraries)  $(facilities_libraries)  $(DatabaseSvc_libraries)  $(RelTable_libraries)  $(EmcRecGeoSvc_libraries)  $(MucGeomSvc_libraries)  $(G4Geo_libraries)  $(Identifier_libraries)  $(ROOTGeo_libraries)  $(BesTimerSvc_libraries)  $(BesPolicy_libraries)  $(BesCxxPolicy_libraries)  $(GaudiInterface_libraries)  $(GdmlToG4_libraries)  $(BesGeant4_libraries)  $(BesCLHEP_libraries)  $(MYSQL_libraries)  $(Sqlite_libraries)  $(GdmlToRoot_libraries)  $(GdmlManagement_libraries)  $(LessTif_libraries)  $(BesExternalArea_libraries)  $(ExternalPolicy_libraries)  $(GaudiKernel_libraries)  $(GaudiPolicy_libraries)  $(BesFortranPolicy_libraries)  $(Reflex_libraries)  $(BesROOT_libraries)  $(ROOT_libraries)  $(GCCXML_libraries)  $(Boost_libraries)  $(Python_libraries)  $(HepMC_libraries)  $(CLHEP_libraries)  $(HepPDT_libraries)  $(XercesC_libraries)  $(CERNLIB_libraries)  $(CASTOR_libraries)  $(cernlib_libraries)  $(LCG_Settings_libraries)  $(ExternalComponents_libraries)  $(LCG_Configuration_libraries)  $(Xt_libraries) 
OmegaKKAlg_use_linkopts=  $(OmegaKKAlg_linkopts)  $(VertexFit_linkopts)  $(ParticleID_linkopts)  $(EvtRecEvent_linkopts)  $(MdcRecEvent_linkopts)  $(TofRecEvent_linkopts)  $(EmcRecEventModel_linkopts)  $(MucRecEvent_linkopts)  $(ExtEvent_linkopts)  $(DstEvent_linkopts)  $(EvTimeEvent_linkopts)  $(MdcGeomSvc_linkopts)  $(MagneticField_linkopts)  $(McTruth_linkopts)  $(EventModel_linkopts)  $(calibUtil_linkopts)  $(rdbModel_linkopts)  $(xmlBase_linkopts)  $(CalibData_linkopts)  $(facilities_linkopts)  $(DatabaseSvc_linkopts)  $(RelTable_linkopts)  $(EmcRecGeoSvc_linkopts)  $(MucGeomSvc_linkopts)  $(G4Geo_linkopts)  $(Identifier_linkopts)  $(ROOTGeo_linkopts)  $(BesTimerSvc_linkopts)  $(BesPolicy_linkopts)  $(BesCxxPolicy_linkopts)  $(GaudiInterface_linkopts)  $(GdmlToG4_linkopts)  $(BesGeant4_linkopts)  $(BesCLHEP_linkopts)  $(MYSQL_linkopts)  $(Sqlite_linkopts)  $(GdmlToRoot_linkopts)  $(GdmlManagement_linkopts)  $(LessTif_linkopts)  $(BesExternalArea_linkopts)  $(ExternalPolicy_linkopts)  $(GaudiKernel_linkopts)  $(GaudiPolicy_linkopts)  $(BesFortranPolicy_linkopts)  $(Reflex_linkopts)  $(BesROOT_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(HepMC_linkopts)  $(CLHEP_linkopts)  $(HepPDT_linkopts)  $(XercesC_linkopts)  $(CERNLIB_linkopts)  $(CASTOR_linkopts)  $(cernlib_linkopts)  $(LCG_Settings_linkopts)  $(ExternalComponents_linkopts)  $(LCG_Configuration_linkopts)  $(Xt_linkopts) 
all_constituents= $(constituents)
constituentsclean= install_includesclean configclean install_runtimeclean OmegaKKAlgclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make DatabaseSvc_check_install_scripts OmegaKKAlg_check_install_runtime 
cmt_actions_constituentsclean= OmegaKKAlg_check_install_runtimeclean DatabaseSvc_check_install_scriptsclean makeclean 
